use_frameworks!

platform :ios, '10.0'

target 'SwiftUiCustomAlert_Example' do
  pod 'SwiftUiCustomAlert', :path => '../'

  target 'SwiftUiCustomAlert_Tests' do
    inherit! :search_paths

    
  end
end
